version: '3.8'

services:
  app:
    container_name: devops_app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: 
      - .env
    ports:
      - "8005:8000"
    depends_on:
      - db
    networks:
      - devops_net
    volumes:
      - ./app:/app
      - ./logs:/logs

  db:
    container_name: devops_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3305:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - devops_net

  prometheus:
    container_name: devops_prometheus
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
    ports:
      - "9095:9090"
    networks:
      - devops_net

  grafana:
    container_name: devops_grafana
    image: grafana/grafana
    user: "0" # root 권한으로 실행
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=https://monitor.bbaeggaog.click/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_LOG_LEVEL=debug
      - GF_SERVER_READ_TIMEOUT=300
      - GF_SERVER_WRITE_TIMEOUT=300
      - GF_SERVER_IDLE_TIMEOUT=300
    ports:
      - "3005:3000"
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      # json 파일 위치
    depends_on:
      - prometheus
    networks:
      - devops_net
    
  nginx:
    container_name: devops_nginx
    image: nginx:latest
    restart: always
    ports:
      - "805:80"
      - "447:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt/live/monitor.myserver.com
    depends_on:
      - app
      - grafana
    networks:
      - devops_net

networks:
  devops_net:
    name: devops_net
    driver: bridge

volumes:
  grafana_data:
