global:
  scrape_interval: 15s

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: 'market_exporter'
    static_configs:
      # - targets: ['devops_app:8000']
      - targets: ['devops_app:8000'] # 도커 내부 실행 시
      # host.docker.internal은 맥/윈도우에서만 유효
      # 리눅스나 K8s에서는 IP/서비스명 수정 필요

  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['devops_app:8000']
